DirDepR2.WebUI/Controllers/AdminCursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DirDepR2.Domain.Abstract;
using DirDepR2.Domain.Entities;

namespace DirDepR2.WebUI.Controllers
{
    public class AdminCursoController : Controller
    {

        private ICursoRepository repository;
        private IMateriaRepository materiaRepository;
        private IProfesorRepository profesorRepository;
        public AdminCursoController(ICursoRepository repo, IMateriaRepository repoM, IProfesorRepository repoP)
        {
            repository = repo;
            materiaRepository = repoM;
            profesorRepository = repoP;
        }


        public ActionResult Index()
        {
             return View(repository.Cursos);
        }

        public ViewResult Edit(int ID)
        {
            Curso curso = repository.Cursos.FirstOrDefault(p => p.ID == ID);
            PopulateMateriasDropDownList(curso.IDMateria);
            PopulateProfesorsDropDownList(curso.IDProfesor);
            return View(curso);
        }



        [HttpPost]
        public ActionResult Edit(Curso curso)
        {
            if (ModelState.IsValid)
            {
                repository.SaveCurso(curso);
                TempData["message"] = string.Format("{0} has been saved", curso.CRN);
                return RedirectToAction("Index");
            }
            else
                return View(curso);
        }

        public ViewResult Create()
        {
            PopulateMateriasDropDownList();
            PopulateProfesorsDropDownList();
            return View("Edit", new Curso());
        }



        private void PopulateMateriasDropDownList(object selectedMateria = null)
        {
            var materiasQuery = materiaRepository.Materias;
            //ViewData["Materias"] = new SelectList(materiasQuery, "ID", "Nombre", selectedMateria);
            ViewBag.IDMateria = new SelectList(materiasQuery, "ID", "Nombre", selectedMateria);

        }

        private void PopulateProfesorsDropDownList(object selectedProfesor = null)
        {
            var profesorQuery = profesorRepository.Profesors;
            //ViewData["Profesores"] = new SelectList(profesorQuery,"ID","Nombre",selectedProfesor);
            ViewBag.IDProfesor = new SelectList(profesorQuery,"ID","Nombre",selectedProfesor);

         }

    }
}

DirDepR2.WebUI/Views/AdminCurso/Edit.cshtml
@model DirDepR2.Domain.Entities.Curso
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminCursoLayout.cshtml";
    //var viewMaterias = ViewData["Materias"];
    //var viewProfesores = ViewData["Profesores"];
}


<div class="panel">
    <div class="panel-heading">
        <h3>Curso</h3>
    </div>

    @using (Html.BeginForm("Edit", "AdminCurso"))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.ID)
            @*@Html.HiddenFor(m => m.IDMateria) Por habelo puesto me dio dolores de cabeza y no dejaba actualizar las cosas*@
            @*@Html.HiddenFor(m => m.IDProfesor)*@

            <div class="form-group">
                @*<label>LabelFor reemplaza poner labels</label>>*@
                @Html.LabelFor(m => m.Periodo)
                @Html.TextBoxFor(m => m.Periodo, new { @class = "form-control" })

                @Html.LabelFor(m => m.CRN)
                @Html.TextBoxFor(m => m.CRN, new { @class = "form-control" })

                @Html.LabelFor(m => m.Cupo)
                @Html.TextBoxFor(m => m.Cupo, new { @class = "form-control" })

                @Html.LabelFor(m => m.Grupo)
                @Html.TextBoxFor(m => m.Grupo, new { @class = "form-control" })

                @Html.LabelFor(m => m.Inscritos)
                @Html.TextBoxFor(m => m.Inscritos, new { @class = "form-control" })


                @foreach (var hora in @Model.HoraSalons)
                {
                    <label>Día:</label>
                    @Html.TextBox("Día", @hora.Dia, new { @class = "form-control" })

                    <label>Inicio:</label>
                    @Html.TextBox("Inicio", @hora.HoraInicio.ToString(), new { @class = "form-control" })

                    <label>Fin:</label>
                    @Html.TextBox("Fin", @hora.HoraFin.ToString(), new { @class = "form-control" })
                }



                <label class="control-label" for="IDMateria"></label>
                @Html.DropDownList("IDMateria", null, string.Empty, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.IDMateria)

                

                <label class="control-label" for="IDProfesor"></label>
                @Html.DropDownList("IDProfesor",null, string.Empty, new { @class ="form-control"})
                @Html.ValidationMessageFor(m => m.IDProfesor)

                    

             
            </div>

        </div>


        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to List", "Index", null, new { @class = "btn btn-default" })
        </div>
    }


</div>


@*@Html.DisplayFor(m => m.CRN)<br />
    @Html.DisplayFor(m => m.Cupo)<br />

    @Html.DisplayFor(m => m.Periodo)<br />

    @Html.DisplayFor(m => m.Profesor.Nombre)<br />
    @Html.DisplayFor(m => m.Materia.Nombre)<br />*@

@*@foreach(var hora in @Model.HoraSalons)
    {
        @hora.Dia @hora.HoraInicio @hora.HoraFin <br />
    }*@



@*@Html.DropDownList("algo", (SelectList)ViewData["Materias"]);
@Html.DropDownList("algo2", (SelectList)ViewData["Profesores"]);*@

DirDepR2.WebUI/Views/AdminCurso/Index.cshtml
@model IEnumerable<DirDepR2.Domain.Entities.Curso>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminProfesorLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Cursos</h3>
    </div>

    <table class="table table-striped table-condensed table-bordered">
        <tr>
            <th class="text-right">CRN</th>
            <th class="text-right">Clave</th>
            <th class="text-right">Materia</th>
            <th class="text-right">Grupo</th>
            <th class="text-right">Profesor</th>
            <td class="text-right">Correo</td>
            <th class="text-center">Action</th>
        </tr>
        @foreach (var curso in Model)
        {
            <tr>
                <td class="text-right">@curso.CRN</td>
                <td class="text-right">@curso.Materia.ClaveMateria</td>
                <td>@Html.ActionLink(curso.Materia.Nombre, "Edit", new { curso.ID })</td>
                <td class="text-right">@curso.Grupo</td>
                <td class="text-right">@curso.Profesor.Nombre</td>
                <td class="text-right">@curso.Profesor.Correo</td>
                <td class="text-center">
                    @using (Html.BeginForm("Delete", "AdminCurso"))
                    {
                        @Html.Hidden("ID", curso.ID)
                        <input type="submit" class="btn btn-default btn-xs" value="Delete" />
                    }


                </td>
            </tr>
        }

    </table>

    <div class="panel-footer">
        @Html.ActionLink("Add a new Course", "Create", null, new { @class = "btn btn-default" })
    </div>

</div>