DirDepR2.WebUI/Controllers/EvaluacionExtraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DirDepR2.Domain.Abstract;
using DirDepR2.Domain.Entities;
using DirDepR2.WebUI.Models;


namespace DirDepR2.WebUI.Controllers
{
    public class EvaluacionExtraController : Controller
    {

        private IStoreProcedures storeProcedure;
        private IProfesorRepository profesorRepository;

        public EvaluacionExtraController(IStoreProcedures storeP, IProfesorRepository repo)
        {
            storeProcedure = storeP;
            profesorRepository = repo;
        }


        public ActionResult Index()
        {
            return View();
        }

        public ViewResult ListaPorProfesor(string nomina)
        {
            PuntosExtraViewModel puntosExtra = new PuntosExtraViewModel
            {
                PuntosExtra = storeProcedure.regresaPuntosExtras(nomina),
                Profesor = profesorRepository.Profesors.FirstOrDefault(p => p.Nomina==nomina)
                
            };
            return View(puntosExtra);
        }


    }
}

DirDepR2.WebUI/Views/EvaluacionExtra/Index.cshtml
@{
    ViewBag.Title = "Puntos Extras";
}

<div class="container">
    @using (Html.BeginForm("ListaPorProfesor", "EvaluacionExtra"))
    {
        @Html.TextBox("Nomina")
       <input type="submit" value="Buscar" />
    }
</div>



@*@Html.ActionLink("Revisar Santillan", "ListaPorProfesor", "EvaluacionExtra", new{Nomina = "L01210856"},null )*@

DirDepR2.WebUI/Views/EvaluacionExtra/ListaPorProfesor.cshtml
@model DirDepR2.WebUI.Models.PuntosExtraViewModel
@{
    ViewBag.Title = "Puntos Extras";
}

<div class="container">

    <img src="~/Content/Images/LogoITESM.jpg" />
    <p class="lead">Profesor: @Model.Profesor.Nombre @Model.Profesor.ApellidoPaterno @Model.Profesor.ApellidoMaterno</p>

    <h4>Por medio de la presente me permito solicitar a usted que asigne los puntos correspondientes a la calificación del alumno</h4>

    <table class="table table-bordered">
        <thead>
            <tr>
                <td class="text-primary">Matrícula</td>
                <td class="text-primary">Alumno</td>
                <td class="text-primary">Clave</td>
                <td class="text-primary">Materia</td>
                <td class="text-primary">Ponderación</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var extra in @Model.PuntosExtra)
            {
                <tr class="active">
                    <td>@extra.Matricula</td>
                    <td>@extra.NombreCompleto</td>
                    <td>@extra.ClaveMateria</td>
                    <td>@extra.Nombre</td>
                    <td>@extra.Ponderacion</td>

                </tr>
            }
        </tbody>

    </table>
    <h4>Sin otro particular por el momento, quedo a sus órdenes para cualquier aclaración al respecto. </h4>
</div>