DirDepR2.WebUI/Controllers/AdminMateriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DirDepR2.Domain.Abstract;
using DirDepR2.Domain.Entities;

namespace DirDepR2.WebUI.Controllers
{
    public class AdminMateriaController : Controller
    {
        private IMateriaRepository repository;
        
        public AdminMateriaController(IMateriaRepository repo)
        {
            repository = repo;
        }

        public ActionResult Index(string searchString)
        {
            if(!string.IsNullOrEmpty(searchString))
            { 
            return View(repository.Materias.Where(n=>n.Nombre.Contains(searchString)||n.ClaveMateria.Contains(searchString)));
            }
            else
                return View(repository.Materias);
        }


        public ViewResult Edit(int ID)
        {
            Materia materia = repository.Materias.FirstOrDefault(p => p.ID == ID);
            return View(materia);
        }

        [HttpPost]
        public ActionResult Edit(Materia materia )
        {
            if (ModelState.IsValid)
            {
                repository.SaveMateria(materia);
                TempData["message"] = string.Format("{0} has been saved", materia.Nombre);
                return RedirectToAction("Index");
            }
            else
                return View(materia);
        }

        public ViewResult Create()
        {
            return View("Edit", new Materia());
        }

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            Materia deleteMateria = repository.DeleteMateria(ID);
            if (deleteMateria != null)
            {
                TempData["message"] = string.Format("{0} was deleted", deleteMateria.Nombre);
            }
            return RedirectToAction("Index");
        }

    }
}

DirDepR2.WebUI/Views/AdminMateria/Edit.cshtml
@model DirDepR2.Domain.Entities.Materia
@{
    ViewBag.Title = "Admin: Edit" + @Model.Nombre;
    Layout = "~/Views/Shared/_AdminMateriaLayout.cshtml";
}

<h1>Materia: @Model.Nombre</h1>

<div class="panel">
    <div class="panel-heading">
        <h3>Edit: @Model.Nombre</h3>
    </div>
    @using (Html.BeginForm("Edit", "AdminMateria"))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.ID) @*Esto en realidad no hace que no se muestre*@
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                if (property.PropertyName != "ID" && property.PropertyName != "Cursoes")
                {
                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                    </div>
                }
            }
            @*@foreach (var m in Model.Cursoes)
                {
                    <p>@Html.DisplayFor(modelItem => m.Materia)</p>
                }*@


        </div>

        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to List", "Index", null, new { @class = "btn btn-default" })
        </div>
    }

</div>

DirDepR2.WebUI/Views/AdminMateria/Index.cshtml
@model IEnumerable<DirDepR2.Domain.Entities.Materia>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminProfesorLayout.cshtml";
}

<div class="panel panel-default">

    <div class="panel-heading">
        <h3>Materias</h3>
    </div>

    <div class="panel-body">
        @using(Html.BeginForm())
        {
            <p>Find by name: @Html.TextBox("searchString")
            <input type="submit" value="Search" />
            </p>
        }


        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">Clave</th>
                <th>Nombre</th>
                <th class="text-right">Unidades</th>
                <th class="text-center">Action</th>
            </tr>
            @foreach (var materia in Model)
            {
                <tr>
                    <td class="text-right">@materia.ClaveMateria</td>
                    <td>@Html.ActionLink(materia.Nombre, "Edit", new { materia.ID })</td>
                    <td class="text-right">@materia.Unidades</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "AdminMateria"))
                        {
                            @Html.Hidden("ID", materia.ID)
                            <input type="submit" class="btn btn-default btn-xs" value="Delete" />
                        }


                    </td>
                </tr>
            }

        </table>

    </div>

    <div class="panel-footer">
        @Html.ActionLink("Añadir nueva materia", "Create", null, new { @class = "btn btn-default" })
    </div>

</div>