DirDepR2.WebUI/Models/HorarioProfesorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DirDepR2.Domain.Entities;

namespace DirDepR2.WebUI.Models
{
    public class HorarioProfesorViewModel
    {
        public IEnumerable<RegresaHorarioProfesor_Result> Horario { set; get; }
        public Profesor Profesor { set; get; }
    }
}

DirDepR2.WebUI/Controllers/HorarioProfesorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DirDepR2.Domain.Abstract;
using DirDepR2.Domain.Entities;
using DirDepR2.WebUI.Models;


namespace DirDepR2.WebUI.Controllers
{
    public class HorarioProfesorController : Controller
    {
         private IStoreProcedures storeProcedure;
        private IProfesorRepository profesorRepository;

        public HorarioProfesorController(IStoreProcedures storeP, IProfesorRepository repo)
        {
            storeProcedure = storeP;
            profesorRepository = repo;
        }
        
        // GET: HorarioProfesor
        public ActionResult Index()
        {
            return View();
        }


        public ViewResult Horario(string nomina)
        {
            HorarioProfesorViewModel horarioProfesor = new HorarioProfesorViewModel
            {
                Horario = storeProcedure.regresaHorarioProfesor(nomina.Trim()),
                Profesor = profesorRepository.Profesors.FirstOrDefault(p => p.Nomina == nomina.Trim())

            };
            return View(horarioProfesor);
        }
        


    }
}

DirDepR2.WebUI/Views/HorarioProfesor/Horario.cshtml
@model DirDepR2.WebUI.Models.HorarioProfesorViewModel
@{
    ViewBag.Title = "Puntos Extras";
}

<div class="container">

    <img src="~/Content/Images/LogoITESM.jpg" />
    <p class="lead">Profesor: @Model.Profesor.Nombre @Model.Profesor.ApellidoPaterno @Model.Profesor.ApellidoMaterno</p>

    <table class="table table-bordered">
        <thead>
            <tr>
                <td class="text-primary">Clave</td>
                <td class="text-primary">Materia</td>
                <td class="text-primary">Clave</td>
                <td class="text-primary">Dia</td>
                <td class="text-primary">Salón</td>
                <td class="text-primary">Inicio</td>
                <td class="text-primary">Fin</td>
           
        </thead>
        <tbody>
            @foreach (var extra in @Model.Horario.ToList())
            {
                <tr class="active">
                    <td>@extra.ClaveMateria</td>
                    <td>@extra.Nombre</td>
                    <td>@extra.Dia</td>
                    <td>@extra.NumeroSalon</td>
                    <td>@extra.Dia</td>
                    <td>@extra.HoraInicio</td>
                    <td>@extra.HoraFin</td>
                        

                </tr>
            }
        </tbody>

    </table>
    <h4>Sin otro particular por el momento, quedo a sus órdenes para cualquier aclaración al respecto. </h4>
</div>

DirDepR2.WebUI/Views/HorarioProfesor/Index.cshtml
@{
    ViewBag.Title = "Horario";
}

<div class="container">
    @using (Html.BeginForm("Horario", "HorarioProfesor"))
    {
        @Html.TextBox("Nomina")
        <input type="submit" value="Buscar" />
    }
</div>